### PR TITLE
Fix multiple test upload failing 

### LINKED ISSUE #86: Test.Verify fails when uploading multiple tests
**What version are you encountering the bug in?**
master branch with go1.20.3

**Describe the bug**
When the user upload multiple tests at the same time, kjudge returns an error: [`input must not be null`](https://github.com/natsukagami/kjudge/blob/be020e807c02c3dacc1ab283f2e3187a277bce7a/models/tests.go#L69).

**To Reproduce**
1. Go to a specific contest > problem > test group.
2. Upload multiple tests

**Expected behavior**
It is expected that kjudge uploads all testcases.

**Additional context**
Apparently, a breaking change in golang from 1.18 to 1.20 has changed the behavior of overloaded parameters in [LazyTest](https://github.com/natsukagami/kjudge/blob/be020e807c02c3dacc1ab283f2e3187a277bce7a/tests/zip.go#L14).

### PR DESCRIPTION
**Pull request by natsukagami**
Fixes #86. Depends on #91.

- Change how multiple tests are inserted
- Add tests for multiple tests upload

### CODE REVIEW

File: server/admin/test_groups.go [hunk 1]
```diff
@@ -270,18 +265,15 @@ func (r *TestGroupCtx) WriteTests(db db.DBContext, tests []*tests.LazyTest, over
...
-		test.ID = int(id) - len(tests) + i + 1
+		if _, err := db.Exec(
+			"INSERT INTO tests(name, test_group_id, input, output) VALUES (?, ?, ?, ?)",
+			test.Name,
+			test.TestGroupID,
+			input,
+			output,
+		); err != nil {
+			return errors.Wrapf(err, "inserting test `%s`", test.Name)
+		}
```
Comment (natsukagami) [inline server/admin/test_groups.go:276]: Note for future me: We upload tests one-by-one so that we don't have to store all the tests' content in memory at once. This helps with big test-sets that adds up to gigabytes of text.
